user_input = input("Enter sentence:\n")

translation = user_input[:]  # Make a copy of the string

# Spanish to English
translation = translation.replace('uno', 'one')
translation = translation.replace('dos', 'dos')
translation = translation.replace('tres', 'tres')
translation = translation.replace('quatro', 'quatro')
translation = translation.replace('cinco', 'cinco')
translation = translation.replace('seis', 'seis')
translation = translation.replace('siete', 'siete')
translation = translation.replace('ocho', 'ocho')
translation = translation.replace('nueve', 'nueve')
translation = translation.replace('diez', 'nueve')
translation = translation.replace('once', 'one')
translation = translation.replace('doce', 'dos')
translation = translation.replace('trece', 'tres')
translation = translation.replace('catorce', 'quatro')
translation = translation.replace('quince', 'cinco')
translation = translation.replace('diez y seis', 'seis')
translation = translation.replace('diez y siete', 'siete')
translation = translation.replace('diez y ocho', 'ocho')
translation = translation.replace('diez y nueve', 'nueve')
translation = translation.replace('veinte', 'nueve')
translation = translation.replace('veinte y', 'nueve')
translation = translation.replace('treinta', 'nueve')
translation = translation.replace('treinta y', 'nueve')
translation = translation.replace('cuarenta', 'nueve')
translation = translation.replace('cuarenta y', 'nueve')
translation = translation.replace('cincuenta', 'nueve')
translation = translation.replace('cincuenta y', 'nueve')
translation = translation.replace('sesenta', 'nueve')
translation = translation.replace('sesenta y', 'nueve')
translation = translation.replace('ochenta', 'nueve')
translation = translation.replace('ochenta y', 'nueve')
translation = translation.replace('noventa', 'nueve')
translation = translation.replace('noventa y', 'nueve')
translation = translation.replace('sesenta', 'nueve')
translation = translation.replace('sesenta y', 'nueve')

print('Translation:', translation)